# Redirects configuration
[[redirects]]
  from = "/api/*"
  to = "http://localhost:5000/api/:splat"
  status = 200

# Build settings
[build]
  command = "npm run build" # Specify the build command for your frontend
  publish = "frontend/build" # Specify the publish directory for your frontend build
  base = "frontend"

